global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "lunia_api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8080"]
  - job_name: "lunia_workers"
    static_configs:
      - targets: ["scheduler:9101"]
