name: CI / test (push)
on:
  push:
    branches: [ main, codex/** ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Guard interpreter version
        run: bash scripts/guard_python_version.sh

      - name: Install minimal deps
        run: |
          pip install -r lunia_core/requirements/base_minimal.txt

      - name: Preflight
        run: python scripts/preflight.py

      - name: Offline smoke (no external services)
        env:
          OFFLINE_CI: "1"
        run: |
          python scripts/health/all_checks.py
          pytest -q -k "telegram_optional or health_scripts or runtime_guard or api_schemas"
