name: CI / test
on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OFFLINE_CI: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PYTHON: "python3.11"
    steps:
      - uses: actions/checkout@v4

      - name: Use Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Guard Python version (==3.11)
        run: bash scripts/guard_python_version.sh 3.11

      - name: Install minimal deps (offline-friendly)
        run: |
          python -m pip install -U pip
          pip install -r lunia_core/requirements/base_minimal.txt

      - name: Ensure no telegram deps in minimal profile
        run: bash scripts/ensure-no-telegram.sh

      - name: Preflight checks
        run: python scripts/preflight.py

      - name: Run smoke tests (health + telegram_optional)
        run: |
          pytest -q -k "health_scripts or telegram_optional" --disable-warnings
