name: Verify

on:
  push:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix['python-version'] }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lunia_core/requirements/dev.txt
      - name: Run verification suite
        working-directory: lunia_core
        run: make verify
      - name: Run integration tests
        working-directory: lunia_core
        run: pytest -q tests/integration
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: verify-artifacts
          path: artifacts

  ui-e2e:
    needs: verify
    runs-on: ubuntu-22.04
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lunia_core/requirements/dev.txt
          playwright install --with-deps chromium
      - name: Run Playwright tests
        env:
          PLAYWRIGHT_BROWSERS_PATH: 0
        run: |
          cd lunia_core
          pytest -q tests/frontend/e2e || echo "Playwright suite completed with non-blocking status"
      - name: Upload e2e artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-e2e-artifacts
          path: artifacts
