name: Verify (Phase 2A)
on: [push, pull_request]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install minimal deps
        run: pip install -r lunia_core/requirements/base_minimal.txt
      - name: Preflight
        run: python scripts/preflight.py
      - name: Guard
        run: bash scripts/ensure-no-telegram.sh
      - name: Health (OFFLINE)
        run: OFFLINE_CI=1 python scripts/health/all_checks.py
      - name: Smoke tests
        run: pytest -q -k "telegram_optional or health_scripts"
