name: Verify
on: [push, pull_request]

jobs:
  system_audit:
    runs-on: ubuntu-latest
    env:
      OFFLINE_CI: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Preflight (typos & minimal guards)
        run: |
          python scripts/preflight.py
          bash scripts/ensure-no-telegram.sh

      - name: Full System Audit (repo-wide)
        run: bash scripts/audit/run_audit.sh

      - name: Offline-safe tests (no external deps)
        run: pytest -q -k "not external"

      - name: Infra health (offline-aware)
        run: python scripts/health/all_checks.py
